### ISSUE TITLE
没有反应啊

### ISSUE THREAD

**Issue by crystoneme** [zhenze12345/ximalaya#2]
fetching audio list ...
fetching audio url ...
starting downloads ...
all the operations succeed

**Comment by zhenze12345** [comment]
没有取到音频列表，给我看看你的参数
下面是个列子：
./ximalya.pl http://www.ximalaya.com/11129614/album/2872220
下载上面这个网页里面的所有音频
或者
./ximalya.pl http://www.ximalaya.com/11129614/album/2872220 侯景传
下载上面这个网页里面的所有标题中包含“侯景传”这个词的音频

**Comment by zhenze12345** [comment]
前两天也有个人给我邮件写了这个问题，我发现给url参数的时候是用的单独的音乐网页
http://www.ximalaya.com/45692914/sound/27966292
而不是专辑的网页
http://www.ximalaya.com/45692914/album/6329320
你是不是也是相同的问题

**Comment by crystoneme** [comment]
好了，按照你的方法成功下载。
不过，这样下载一个专辑很方便。但是如果专辑有更新，每次都重下一遍，也不好啊
希望增加单独下载的功能。

**Comment by zhenze12345** [comment]
我记得如果有更新的话，是可以跳过已经下载过的，关于sound的功能，等我有时间我可以加一下

**Comment by zhenze12345** [comment]
已经加上这个功能了，可以的话帮我测试一下:)
